baseURL = "/"
languageCode = "en-us"
title = "Vítor Bichara"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Vítor Bichara"
    description = "Desenvolvedor Full Stack"
    githubUsername = "vittis"
    accent = "#1a7d8b"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Início"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projetos/"
    name = "Projetos"
    weight = 3

[[menu.main]]
    url = "/contato/"
    name = "Contato"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:vitbolb1@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/vitt94"
    name = "facebook-square"
    weight = 2

[[menu.icon]]
    url = "https://www.instagram.com/v.bichara/"
    name = "instagram"
    weight = 3

[[menu.icon]]
    url = "https://github.com/vittis"
    name = "github"
    weight = 4



#[[menu.icon]]
 #   url = "https://www.linkedin.com/in/username/"
 #   name = "linkedin"
 #   weight = 4

#[[menu.icon]]
 #   url = "https://www.stackoverflow.com/username/"
  #  name = "stack-overflow"
  #  weight = 5
